disabled_rules: # rule identifiers to exclude from running
  - force_cast
  - force_try
  - type_name
  - variable_name
  - function_body_length
  - line_length
  - type_body_length
  - variable_name_max_length
  - variable_name_min_length
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
